Depth quantization
robotology/yarp-device-realsense2 pull request #30
Opened 2022-05-19 15:39 UTC by ste93

based on #29, this adds the quantization of the realsense in order to save some bandwidth  with the compression (as made in gazebo https://github.com/robotology/gazebo-yarp-plugins/pull/608)

2022-05-19 16:10 UTC, ste93 commented
@randaz81 @elandini84 @DatSpace fyi

2022-05-20 08:08 UTC, Nicogene commented on src/devices/realsense2/realsense2Driver.cpp
> +                        ( Frame.getRawImageSize()  -(( i-1) * bytesPerPixel(format))) + pixelIndex];
This change of sign was a bug?

2022-05-20 08:09 UTC, Nicogene approved these changes
LGTM, just a clarification on a small change

2022-05-20 08:11 UTC, Nicogene commented
Ah could you please add a line in the changelog? Thanks!

2022-05-20 10:01 UTC, ste93 commented on src/devices/realsense2/realsense2Driver.cpp
> +                        ( Frame.getRawImageSize()  -(( i-1) * bytesPerPixel(format))) + pixelIndex];
yes

2022-05-20 10:17 UTC, DatSpace commented
The nearplane and farplane dont seem to be used. So the could be removed right ?

2022-05-20 13:19 UTC, ste93 commented
yep they are a leftover, I'll remove them

2022-05-23 11:20 UTC, ste93 commented on src/devices/realsense2/realsense2Driver.cpp
> +    double farPlane;
```suggestion
```

2022-06-07 16:48 UTC, traversaro commented on src/devices/realsense2/realsense2Driver.cpp
> +    double farPlane;
So this can be ignored?

2022-06-07 16:49 UTC, traversaro commented
Thanks, if no one objects we can merge as soon as the CI is happy.

2022-06-07 17:09 UTC, traversaro commented
The reported error is:
~~~
[1/10] Building CXX object src/devices/realsense2/CMakeFiles/yarp_realsense2.dir/realsense2Driver.cpp.o
FAILED: src/devices/realsense2/CMakeFiles/yarp_realsense2.dir/realsense2Driver.cpp.o 
/usr/share/miniconda/envs/test/bin/x86_64-conda-linux-gnu-c++ -Dyarp_realsense2_EXPORTS  -Wall -Wextra -Wsign-compare -Wpointer-arith -Winit-self -Wnon-virtual-dtor -Wcast-align -Wunused -Wunused-but-set-variable -Wvla -Wmissing-include-dirs -Wlogical-op -Wreorder -Wsizeof-pointer-memaccess -Woverloaded-virtual -Wundef -Wredundant-decls -Wunknown-pragmas -Wunused-result -Wc++2a-compat -Wignored-attributes -Wdangling-else -Wmisleading-indentation -Wtautological-compare -Wsuggest-override -Wmaybe-uninitialized  -Wno-unused-parameter  -Wdeprecated-declarations -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /usr/share/miniconda/envs/test/include  -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /usr/share/miniconda/envs/test/include -O3 -DNDEBUG -fPIC -MD -MT src/devices/realsense2/CMakeFiles/yarp_realsense2.dir/realsense2Driver.cpp.o -MF src/devices/realsense2/CMakeFiles/yarp_realsense2.dir/realsense2Driver.cpp.o.d -o src/devices/realsense2/CMakeFiles/yarp_realsense2.dir/realsense2Driver.cpp.o -c /home/runner/work/yarp-device-realsense2/yarp-device-realsense2/src/devices/realsense2/realsense2Driver.cpp
/home/runner/work/yarp-device-realsense2/yarp-device-realsense2/src/devices/realsense2/realsense2Driver.cpp: In member function 'bool realsense2Driver::getImage(realsense2Driver::depthImage&, realsense2Driver::Stamp*, const rs2::frameset&)':
/home/runner/work/yarp-device-realsense2/yarp-device-realsense2/src/devices/realsense2/realsense2Driver.cpp:1129:24: error: 'nearPlane' was not declared in this scope
 1129 |     getDepthClipPlanes(nearPlane, farPlane);
      |                        ^~~~~~~~~
/home/runner/work/yarp-device-realsense2/yarp-device-realsense2/src/devices/realsense2/realsense2Driver.cpp:1129:35: error: 'farPlane' was not declared in this scope
 1129 |     getDepthClipPlanes(nearPlane, farPlane);
      |                                   ^~~~~~~~
/home/runner/work/yarp-device-realsense2/yarp-device-realsense2/src/devices/realsense2/realsense2Driver.cpp: In member function 'virtual bool realsense2Driver::getFeature(int, double*)':
/home/runner/work/yarp-device-realsense2/yarp-device-realsense2/src/devices/realsense2/realsense2Driver.cpp:1299:80: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
 1299 |             b = optionValue2Perc(RS2_OPTION_EXPOSURE, m_color_sensor, (float&) value, valToGet);
      |                                                                                ^~~~~
/home/runner/work/yarp-device-realsense2/yarp-device-realsense2/src/devices/realsense2/realsense2Driver.cpp:1303:76: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
 1303 |             b = optionValue2Perc(RS2_OPTION_GAIN, m_color_sensor, (float&) value, valToGet);
      |                                                                            ^~~~~
/home/runner/work/yarp-device-realsense2/yarp-device-realsense2/src/devices/realsense2/realsense2Driver.cpp:1313:85: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
 1313 |             b = optionValue2Perc(RS2_OPTION_WHITE_BALANCE, m_color_sensor, (float&) value, valToGet);
      |                                                                                     ^~~~~
/home/runner/work/yarp-device-realsense2/yarp-device-realsense2/src/devices/realsense2/realsense2Driver.cpp:1317:81: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
 1317 |             b = optionValue2Perc(RS2_OPTION_SHARPNESS, m_color_sensor, (float&) value, valToGet);
      |                                                                                 ^~~~~
/home/runner/work/yarp-device-realsense2/yarp-device-realsense2/src/devices/realsense2/realsense2Driver.cpp:1321:75: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
 1321 |             b = optionValue2Perc(RS2_OPTION_HUE, m_color_sensor, (float&) value, valToGet);
      |                                                                           ^~~~~
/home/runner/work/yarp-device-realsense2/yarp-device-realsense2/src/devices/realsense2/realsense2Driver.cpp:1325:82: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
 1325 |             b = optionValue2Perc(RS2_OPTION_SATURATION, m_color_sensor, (float&) value, valToGet);
      |                                                                                  ^~~~~
~~~

2022-06-07 17:10 UTC, traversaro requested changes
See CI.

2022-06-08 10:10 UTC, traversaro commented
Thanks!

2022-06-08 10:10 UTC, merged