Add Angular Acceleration and Linear Velocity Values
robotology/yarp-device-realsense2 pull request #48
Opened 2024-11-13 15:01 UTC by nicktrem

Upon the acceptance of [the corresponding YARP pull request](https://github.com/robotology/yarp/pull/3149), this pull request will allow access to the measured Angular Acceleration and Linear Velocity values from supported Realsense devices.

2024-11-14 14:34 UTC, Nicogene requested changes
Some minor comments, I would add the required YARP version that includes the new methods of the MAS interface

(I re-enabled the CI that was disabled for inactivity)

2024-11-14 14:34 UTC, Nicogene commented on src/devices/realsense2/realsense2Tracking.cpp
> +    sensors[0].set_option(RS2_OPTION_ENABLE_POSE_JUMPING, 0.f);
Is this option available for all the sensors?

2024-11-14 14:34 UTC, Nicogene commented on src/devices/realsense2/realsense2Tracking.cpp
> +    out.resize(19);
Isn't possible to use a variable instead of `19` ? Or get it from the size of some realsense data structure.
Because I saw that the same magic number is used in `getChannels`, and it could happen that if the two can be inconsistent if we don't use a variable for handling it.

2024-11-16 15:41 UTC, nicktrem commented on src/devices/realsense2/realsense2Tracking.cpp
> +    sensors[0].set_option(RS2_OPTION_ENABLE_POSE_JUMPING, 0.f);
No, this option is only available for sensors that calculate the sensor's pose internally (namely the Realsense T265). This is a hard-coded option that was left in by mistake. This option was initially added because we required it for our robot testing. It has been removed in [3496b47](https://github.com/robotology/yarp-device-realsense2/pull/48/commits/3496b477835ab2b9c1ecd44102d3e3c2a0127f12)

2024-12-05 12:56 UTC, nicktrem commented
> Some minor comments, I would add the required YARP version that includes the new methods of the MAS interface
> 
> (I re-enabled the CI that was disabled for inactivity)

@Nicogene This will be done once the YARP version with the changes specified in [this PR](https://github.com/robotology/yarp/pull/3149) is released, until then we will wait patiently :smile:

2024-12-12 11:41 UTC, traversaro commented
@nicktrem now that https://github.com/robotology/yarp/pull/3149 has been merged, if you like we can merge this PR in an experimental branch in this repo, if it simplifies the usage downstream. I would just avoid to merge it to `master` as that branch is meant to be compatible with releases YARP versions.

2024-12-12 14:10 UTC, traversaro commented
Ack! The CI will be broken unless we switch to building YARP from source, but as I do not expect a lot of traffic in the `devel` branch, I think that is ok. @Nicogene are your comments addressed?

2024-12-12 14:11 UTC, traversaro commented on src/devices/realsense2/realsense2Tracking.cpp
> +    out[18] = m_last_pose.angular_acceleration.z;
Are you using this port? If not I would just leave it as it was before, as the `IAnalogSensor` interface is mostly deprecated, and if we add features people may want to use it. @nicktrem

2024-12-12 14:45 UTC, nicktrem commented on src/devices/realsense2/realsense2Tracking.cpp
> +    out[18] = m_last_pose.angular_acceleration.z;
We do not use this port, I agree with you. This has been fixed in [cce5f2c](https://github.com/robotology/yarp-device-realsense2/pull/48/commits/cce5f2cbb3351a757750505cb5eb8db40039ebea)

2024-12-13 16:21 UTC, Nicogene commented
> Ack! The CI will be broken unless we switch to building YARP from source, but as I do not expect a lot of traffic in the `devel` branch, I think that is ok. @Nicogene are your comments addressed?

Yes!

2024-12-13 16:21 UTC, Nicogene approved these changes

2024-12-13 16:30 UTC, merged

2024-12-13 16:31 UTC, traversaro commented
Thanks @nicktrem ! Feel free to ping me merge devel in master back in January/February if we have a new YARP release, thanks!

2025-06-06 10:35 UTC, traversaro commented
Great, so we can merge in devel and release, great!